---

language: go
dist: bionic
addons:
  apt:
    packages:
    - git
    - wget
    - unzip

before_script:
  - 'chmod +x .data/prepare.sh'
  - '.data/prepare.sh'
  - 'echo $GOOGLE_CREDENTIALS_FILE | base64 -d > $GOOGLE_CREDENTIALS'

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script:
        - echo "HCL Format check"
        - 'terragrunt hclfmt --terragrunt-check'
        - echo "Validation"
        - terragrunt validate-all2> >(grep -v "\[terragrunt]" >&2)
        - echo "Plan"
        - terragrunt plan-all -lock=false 2> >(grep -v "\[terragrunt]" >&2)
    - stage: deploy
      script: terragrunt apply-all -auto-approve 2> >(grep -v "\[terragrunt]" >&2)
