---

language: go
dist: bionic
addons:
  apt:
    packages:
    - git
    - wget
    - unzip

before_script:
  - 'chmod +x .data/prepare.sh'
  - '.data/prepare.sh'
  - 'echo $GOOGLE_CREDENTIALS_FILE | base64 -d > $GOOGLE_CREDENTIALS'

stages:
  - name: hclfmt
    if: type != api AND commit_message != "destroy"
  - name: test
    if: type != api AND commit_message != "destroy"
  - name: apply
    if: (commit_message == "apply" OR type = api) AND commit_message != "destroy"
  - name: destroy
    if: type != api AND commit_message = "destroy"

jobs:
  include:
    - stage: hclfmt
      script: terragrunt hclfmt --terragrunt-check
    - stage: test
      script:
        - terragrunt validate-all
        - terragrunt plan-all -lock=false
    - stage: apply
      script: echo y | terragrunt apply-all
    - stage: destroy
      script: echo y | terragrunt destroy-all
