---

language: go
dist: bionic
addons:
  apt:
    packages:
    - git
    - wget
    - unzip

before_script:
  - 'chmod +x .data/prepare.sh'
  - '.data/prepare.sh'
  - 'echo $GOOGLE_CREDENTIALS_FILE | base64 -d > $GOOGLE_CREDENTIALS'

stages:
  - hclfmt
  - test
  - name: apply
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: hclfmt
      script: terragrunt hclfmt --terragrunt-check
    - stage: test
      script:
        - terragrunt validate-all
        - terragrunt plan-all -lock=false
    - stage: apply
      script: echo y | terragrunt apply-all -auto-approve
