---

language: go
dist: bionic
addons:
  apt:
    packages:
    - git
    - wget
    - unzip

before_script:
  - 'chmod +x .data/prepare.sh'
  - '.data/prepare.sh'
  - 'echo $GOOGLE_CREDENTIALS_FILE | base64 -d > $GOOGLE_CREDENTIALS'

stages:
  - name: hclfmt
  - name: test
  - name: apply
    if: branch = master AND (type = api OR commit_message == "apply")
  - name: destroy
    if: branch = master AND (type = api OR commit_message = "destroy")

jobs:
  include:
    - stage: hclfmt
      script: terragrunt hclfmt --terragrunt-check
    - stage: test
      script:
        - terragrunt validate-all
        - terragrunt plan-all -lock=false
    - stage: apply
      script: terragrunt apply-all -auto-approve
    - stage: destroy
      script: terragrunt destroy-all -auto-approve
